/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) throws InterruptedException {
        new EchoServer(8080).start();
    }

}
